DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
);

--CREATE
INSERT INTO TB_HEROIS (NOME, PODER)
VALUES
('FLASH', 'VELOCIDADE'),
('AQUAMAN', 'FALAR COM OS AMINAIS'),
('BATMAN', 'DINHEIRO');

--READ
SELECT * FROM TB_HEROIS;
SELECT NOME FROM TB_HEROIS WHERE ID = 1;

-- UPDATE
UPDATE TB_HEROIS SET NOME = 'GOKU', PODER = 'DEUS' WHERE ID = 3;

-- DELETE 

DELETE FROM TB_HEROIS WHERE ID = 3;